PUBLISHABLE_KEY: 'pk_test_h3DuEFi6li4dKSe8ZcfporXg'
SECRET_KEY: 'sk_test_godFEwMitkzYgLPdIK6fZlUs'
CLIENT_ID: 'ca_2KftikelkQy6qbPR9TxRrtrUNtOpPVQO'
GMAIL_USERNAME: 'c.tnecniv@gmail.com'
GMAIL_PASSWORD: 'vincentchu1'
journeyman: '12_ca'
adventurer: '24_ca'